name: Pre-commit linting

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - name: pre-commit
      run: |
        pip install pre-commit
        git fetch origin master:refs/remotes/origin/master
        pre-commit run --from-ref origin/HEAD --to-ref HEAD
