name: Pre-commit

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup python latest version
      uses: actions/setup-python@v2

    - name: Install Hadolint
      run: |
        apt update && apt install -yqq --no-install-recommends git wget
        wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.18.0/hadolint-Linux-x86_64
        chmod +x /usr/local/bin/hadolint

    - name: Run pre-commit test
      uses: pre-commit/action@v2.0.0
      with:
        extra_args: --config .pre-commit-config-gh.yml
